const fs = require('fs'); const target = process.argv[2] || 'src/views/Editor.tsx'; const raw = fs.readFileSync(target, 'utf8'); const crlf = raw.includes('\r\n'); let source = raw.replace(/\r\n/g, '\n');
function replace(anchor, replacement) { if (source.includes(replacement)) return; if (!source.includes(anchor)) throw new Error(`Editor ability anchor changed: ${anchor.slice(0, 80)}`); source = source.replace(anchor, replacement); }
replace("    if (type === 'wait') nodeData = { ms: '1000' };", "    if (type === 'wait') nodeData = { ms: '1000' };\n    else if (type === 'wait_for_event') nodeData = { eventType: 'webhook', requiredEvents: 1, timeoutMs: 86400000 };\n    else if (type === 'wait_until') nodeData = { at: new Date(Date.now() + 3600000).toISOString() };\n    else if (type === 'approval') nodeData = { context: '', email: '', timeoutMs: 86400000 };");
replace("      wait: 'Delay Timer',", "      wait: 'Delay Timer',\n      wait_for_event: 'Wait for Event',\n      wait_until: 'Wait Until',\n      approval: 'Human Approval',");
replace("            <button className=\"node-item btn-node\" onClick={() => addNode('wait')}><Clock size={14}/> Delay Timer</button>", "            <button className=\"node-item btn-node\" onClick={() => addNode('wait')}><Clock size={14}/> Delay Timer</button>\n            <button className=\"node-item btn-node\" onClick={() => addNode('wait_for_event')}><Clock size={14}/> Wait for Event</button>\n            <button className=\"node-item btn-node\" onClick={() => addNode('wait_until')}><Clock size={14}/> Wait Until</button>\n            <button className=\"node-item btn-node\" onClick={() => addNode('approval')}><Clock size={14}/> Human Approval</button>");
const propertyAnchor = `                {currentNode.data.type === 'open_tab' && (`;
const propertyReplacement = `                {currentNode.data.type === 'wait_for_event' && (<><div className="form-group"><label>Event Type</label><select className="form-input" value={currentNode.data.data?.eventType || 'webhook'} onChange={(e) => updateNodeDataField('eventType', e.target.value)}><option value="webhook">Webhook</option><option value="reply">Reply</option><option value="file">File</option><option value="external_state">External state</option></select></div><div className="form-group"><label>Required Events</label><input type="number" min="1" max="100" className="form-input" value={currentNode.data.data?.requiredEvents || 1} onChange={(e) => updateNodeDataField('requiredEvents', Number(e.target.value))}/></div><div className="form-group"><label>Timeout (ms)</label><input type="number" className="form-input" value={currentNode.data.data?.timeoutMs || 86400000} onChange={(e) => updateNodeDataField('timeoutMs', Number(e.target.value))}/></div></>)}
                {currentNode.data.type === 'wait_until' && (<div className="form-group"><label>Resume At</label><input type="datetime-local" className="form-input" value={String(currentNode.data.data?.at || '').slice(0,16)} onChange={(e) => updateNodeDataField('at', new Date(e.target.value).toISOString())}/></div>)}
                {currentNode.data.type === 'approval' && (<><div className="form-group"><label>Approval Context</label><textarea className="form-input" value={currentNode.data.data?.context || ''} onChange={(e) => updateNodeDataField('context', e.target.value)}/></div><div className="form-group"><label>Approver Email</label><input className="form-input" value={currentNode.data.data?.email || ''} onChange={(e) => updateNodeDataField('email', e.target.value)}/></div></>)}

${propertyAnchor}`;
replace(propertyAnchor, propertyReplacement);
fs.writeFileSync(target, crlf ? source.replace(/\n/g, '\r\n') : source); console.log(`Applied durable wait and approval editor controls to ${target}.`);
