import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, FlaskConical, History, Loader2, Network, Plus, RefreshCw, Rocket, SearchCheck, ShieldCheck, Undo2, X } from 'lucide-react';
import { toast } from 'sonner';
import { applyConnectorRepair, approveConnector, generateConnector, inspectConnector, listConnectors, listVersions, proposeConnectorRepair, publishConnector, rollbackConnector, testConnector, type ConnectorArtifact } from './connectorClient';

const stateTone: Record<string, string> = { generated: 'bg-slate-100 text-slate-600', inspected: 'bg-blue-50 text-blue-700', tested: 'bg-amber-50 text-amber-700', approved: 'bg-violet-50 text-violet-700', published: 'bg-emerald-50 text-emerald-700', rejected: 'bg-rose-50 text-rose-700', retired: 'bg-slate-100 text-slate-500' };

export function ConnectorWorkbench() {
  const [items, setItems] = useState<ConnectorArtifact[]>([]); const [selectedId, setSelectedId] = useState(''); const [versions, setVersions] = useState<ConnectorArtifact[]>([]);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [createOpen, setCreateOpen] = useState(false);
  const selected = useMemo(() => versions.find((item) => item.connectorId === selectedId) || items.find((item) => item.connectorId === selectedId) || null, [items, versions, selectedId]);
  const load = async () => { setLoading(true); setError(''); try { const next = await listConnectors(); setItems(next); setSelectedId((id) => id || next[0]?.connectorId || ''); } catch (e) { setError(e instanceof Error ? e.message : 'Connectors could not be loaded.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (!selectedId) return; listVersions(selectedId).then(setVersions).catch(() => setVersions([])); }, [selectedId]);
  const act = async (label: string, operation: () => Promise<ConnectorArtifact>) => { setBusy(label); try { const result = await operation(); toast.success(`${result.name}: ${label} complete`); await load(); setVersions(await listVersions(result.connectorId)); } catch (e) { toast.error(e instanceof Error ? e.message : `${label} failed.`); } finally { setBusy(''); } };
  const totalRuns = items.reduce((sum, item) => sum + Number(item.successCount || 0) + Number(item.failureCount || 0), 0); const successes = items.reduce((sum, item) => sum + Number(item.successCount || 0), 0);
  return <main className="h-full overflow-y-auto bg-[#F8F6F1] p-5 md:p-7"><div className="mx-auto max-w-[1500px] space-y-5">
    <header className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-[#6C47FF]"><Network size={15}/> Universal integrations</div><h1 className="text-2xl font-bold text-slate-900">Connector workbench</h1><p className="mt-1 text-sm text-slate-500">Generate once, inspect and approve, then execute deterministically.</p></div><div className="flex gap-2"><button onClick={() => void load()} className="rounded-xl border bg-white px-3 py-2 text-xs font-bold"><RefreshCw size={14} className={loading ? 'animate-spin' : ''}/></button><button onClick={() => setCreateOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#6C47FF] px-4 py-2 text-xs font-bold text-white"><Plus size={14}/> New connector</button></div></header>
    <section className="grid gap-3 sm:grid-cols-3">{[['Published', items.filter(i => i.publicationState === 'published').length], ['Deterministic runs', totalRuns], ['Verified success', totalRuns ? `${Math.round(successes / totalRuns * 100)}%` : '—']].map(([label,value]) => <article key={label} className="rounded-2xl border border-[#EAE6DF] bg-white p-4"><p className="text-xl font-bold">{value}</p><p className="text-[11px] font-semibold text-slate-500">{label}</p></article>)}</section>
    <section className="grid min-h-[600px] overflow-hidden rounded-2xl border border-[#EAE6DF] bg-white lg:grid-cols-[340px_1fr]">
      <aside className="border-b bg-[#FDFBF7] lg:border-b-0 lg:border-r">{loading ? <div className="flex h-48 items-center justify-center"><Loader2 className="animate-spin"/></div> : error ? <div className="m-4 rounded-xl bg-rose-50 p-4 text-xs text-rose-700">{error}</div> : !items.length ? <div className="p-10 text-center text-sm text-slate-500">No connectors yet.</div> : <div className="p-2">{items.map(item => <button key={item.connectorId} onClick={() => setSelectedId(item.connectorId)} className={`mb-1 w-full rounded-xl border p-3 text-left ${selectedId === item.connectorId ? 'border-[#6C47FF]/30 bg-[#6C47FF]/5' : 'border-transparent hover:bg-slate-100'}`}><div className="flex justify-between gap-2"><span className="truncate text-xs font-bold">{item.name}</span><span className={`rounded-full px-2 py-0.5 text-[9px] font-bold ${stateTone[item.publicationState]}`}>{item.publicationState}</span></div><p className="mt-1 truncate text-[11px] text-slate-500">{item.operationName} · {item.targetDomains.join(', ')}</p></button>)}</div>}</aside>
      {!selected ? <div className="flex items-center justify-center text-sm text-slate-400">Select a connector.</div> : <div className="p-5 md:p-7"><div className="flex flex-col justify-between gap-4 border-b pb-5 md:flex-row"><div><h2 className="text-lg font-bold">{selected.name} <span className="text-sm text-slate-400">{selected.version}</span></h2><p className="mt-1 text-sm text-slate-500">{selected.description || selected.operationName}</p></div><div className="flex flex-wrap gap-2">{selected.publicationState === 'generated' && <Action icon={SearchCheck} label="Inspect" busy={busy} onClick={() => act('Inspection', () => inspectConnector(selected.connectorId, selected.version))}/>} {selected.publicationState === 'inspected' && <Action icon={FlaskConical} label="Run regressions" busy={busy} onClick={() => act('Testing', () => testConnector(selected.connectorId, selected.version))}/>} {selected.publicationState === 'tested' && <Action icon={ShieldCheck} label="Approve" busy={busy} onClick={() => act('Approval', () => approveConnector(selected.connectorId, selected.version))}/>} {['tested','approved'].includes(selected.publicationState) && <Action icon={Rocket} label="Publish" busy={busy} onClick={() => act('Publication', () => publishConnector(selected.connectorId, selected.version))}/>}</div></div>
        <div className="mt-6 grid gap-5 xl:grid-cols-2"><Info title="Contract"><Row label="Classification" value={selected.readWrite}/><Row label="Methods" value={selected.allowedMethods.join(', ')}/><Row label="Destinations" value={selected.targetDomains.join(', ')}/><Row label="Vault references" value={selected.requiredVaultRefs.length ? selected.requiredVaultRefs.join(', ') : 'None'}/></Info><Info title="Health"><Row label="Successful runs" value={String(selected.successCount || 0)}/><Row label="Failed runs" value={String(selected.failureCount || 0)}/><Row label="Generation cost" value={`${selected.generationCostMicros || 0} μUSD`}/><Row label="Execution cost" value={`${selected.executionCostMicros || 0} μUSD`}/>{selected.lastFailureFingerprint && <button onClick={() => void act('Repair proposal', async () => { const proposal = await proposeConnectorRepair(selected.connectorId, selected.version, selected.lastFailureFingerprint!); if (!window.confirm(`Review repair proposal:\n\n${proposal.rationale || 'Narrow source repair'}\n\nCreate a new draft version?`)) throw new Error('Repair review cancelled.'); return applyConnectorRepair(selected.connectorId, selected.version, proposal.id); })} className="mt-3 inline-flex items-center gap-2 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs font-bold text-amber-800"><FlaskConical size={13}/> Propose repair</button>}</Info></div>
        <section className="mt-6"><h3 className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-500"><History size={14}/> Version history</h3><div className="overflow-hidden rounded-xl border">{versions.map(version => <div key={version.version} className="flex items-center justify-between border-b p-3 last:border-0"><div><p className="text-xs font-bold">{version.version} <span className={`ml-2 rounded-full px-2 py-0.5 text-[9px] ${stateTone[version.publicationState]}`}>{version.publicationState}</span></p><p className="mt-1 text-[10px] text-slate-400">Updated {new Date(version.updatedAt).toLocaleString()}</p></div>{version.publicationState === 'published' && version.version !== selected.version && <button onClick={() => act('Rollback', () => rollbackConnector(version.connectorId, version.version))} className="inline-flex items-center gap-1 text-xs font-bold text-[#6C47FF]"><Undo2 size={13}/> Activate</button>}</div>)}</div></section>
      </div>}
    </section>
  </div>{createOpen && <CreateDialog close={() => setCreateOpen(false)} created={async artifact => { setCreateOpen(false); await load(); setSelectedId(artifact.connectorId); }}/>}</main>;
}
function Action({ icon: Icon, label, busy, onClick }: { icon: typeof CheckCircle2; label: string; busy: string; onClick: () => void }) { return <button disabled={Boolean(busy)} onClick={onClick} className="inline-flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-xs font-bold disabled:opacity-50">{busy === label ? <Loader2 size={14} className="animate-spin"/> : <Icon size={14}/>} {label}</button>; }
function Info({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border bg-[#FDFBF7] p-4"><h3 className="mb-3 text-xs font-bold uppercase tracking-wider text-slate-500">{title}</h3><dl className="space-y-2">{children}</dl></section>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4 text-xs"><dt className="text-slate-500">{label}</dt><dd className="break-all text-right font-semibold text-slate-700">{value}</dd></div>; }
function CreateDialog({ close, created }: { close: () => void; created: (artifact: ConnectorArtifact) => void }) { const [form, setForm] = useState({ name: '', operationName: '', goal: '', domain: '', readWrite: 'read', vaultRefs: '' }); const [saving, setSaving] = useState(false); const submit = async () => { setSaving(true); try { const id = `${form.operationName}-${form.domain}`.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '').slice(0, 80); const artifact = await generateConnector({ connectorId: id, version: 'v1', name: form.name, operationName: form.operationName, goal: form.goal, readWrite: form.readWrite, targetDomains: [form.domain], allowedMethods: form.readWrite === 'write' ? ['POST'] : ['GET'], requiredVaultRefs: form.vaultRefs.split(',').map(v => v.trim()).filter(Boolean), regressionCases: [{ id: 'generated-smoke', label: 'Generated connector smoke test', input: {} }] }); created(artifact); } catch (e) { toast.error(e instanceof Error ? e.message : 'Connector generation failed.'); } finally { setSaving(false); } }; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="font-bold">Generate connector</h2><p className="text-xs text-slate-500">Secrets are referenced by name and never sent to the model.</p></div><button onClick={close}><X size={18}/></button></div><div className="mt-5 grid gap-3">{[['name','Name'],['operationName','Operation name'],['goal','Goal'],['domain','API domain'],['vaultRefs','Vault references (comma-separated)']].map(([key,label]) => <label key={key} className="text-xs font-semibold text-slate-600">{label}<input value={form[key as keyof typeof form]} onChange={e => setForm({...form,[key]:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2 text-sm"/></label>)}<label className="text-xs font-semibold">Classification<select value={form.readWrite} onChange={e => setForm({...form,readWrite:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2"><option value="read">Read only</option><option value="write">Write capable</option></select></label></div><button disabled={saving || !form.name || !form.operationName || !form.domain} onClick={() => void submit()} className="mt-5 w-full rounded-xl bg-[#6C47FF] py-2.5 text-xs font-bold text-white disabled:opacity-50">{saving ? 'Generating…' : 'Generate draft'}</button></div></div>; }
