import { getFreshIdToken } from './firebaseAuth';
const base = (import.meta.env.VITE_RUNNER_URL as string | undefined)?.replace(/\/$/, '');
async function request<T>(path: string, init: RequestInit = {}): Promise<T> { if (!base) throw new Error('Cloud runner is not configured.'); const token = await getFreshIdToken(); if (!token) throw new Error('Sign in required.'); const response = await fetch(`${base}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', ...(init.headers || {}) } }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || `Runner error ${response.status}`); return payload; }
export interface PlatformConfig { contract: { inputSchema: Record<string, unknown>; outputSchema: Record<string, unknown>; outputNodeId?: string | null; description?: string }; modelPolicy: { profile: string; maxModelCalls: number; maxContextChars: number; allowVision: boolean; fallbackEnabled: boolean }; contextPolicy: { defaultVisibility: string; maxObservationChars: number; retainNodeOutputs: number }; regressionCases: Array<{ id: string; input: unknown; expectedOutput?: unknown }>; environments: Record<string, string>; activeProductionReleaseId?: string | null; }
export interface WorkflowRelease { id: string; fingerprint: string; createdAt: string; notes?: string; regression?: { passed: boolean; total: number; passedCount: number }; }
export async function getPlatform(workflowId: string) { return (await request<{ platform: PlatformConfig }>(`/v1/workflows/${encodeURIComponent(workflowId)}/platform`)).platform; }
export async function savePlatform(workflowId: string, platform: PlatformConfig) { return request(`/v1/workflows/${encodeURIComponent(workflowId)}/platform`, { method: 'PUT', body: JSON.stringify(platform) }); }
export async function debugNode(workflowId: string, nodeId: string, input: unknown, mode = 'through') { return request<{ debug: { logs: string[]; scraped: unknown } }>(`/v1/workflows/${encodeURIComponent(workflowId)}/debug`, { method: 'POST', body: JSON.stringify({ nodeId, input, mode }) }); }
export async function listReleases(workflowId: string) { return (await request<{ releases: WorkflowRelease[] }>(`/v1/workflows/${encodeURIComponent(workflowId)}/releases`)).releases; }
export async function createRelease(workflowId: string, notes = '') { return (await request<{ release: WorkflowRelease }>(`/v1/workflows/${encodeURIComponent(workflowId)}/releases`, { method: 'POST', body: JSON.stringify({ notes }) })).release; }
export async function runRegression(workflowId: string, releaseId: string, cases: PlatformConfig['regressionCases']) { return request<{ regression: { passed: boolean; total: number; passedCount: number; results: unknown[] } }>(`/v1/workflows/${encodeURIComponent(workflowId)}/releases/${encodeURIComponent(releaseId)}/regression`, { method: 'POST', body: JSON.stringify({ cases }) }); }
export async function promoteRelease(workflowId: string, releaseId: string, environment: string) { return request(`/v1/workflows/${encodeURIComponent(workflowId)}/releases/${encodeURIComponent(releaseId)}/promote`, { method: 'POST', body: JSON.stringify({ environment }) }); }
export async function rollbackRelease(workflowId: string, releaseId: string) { return request(`/v1/workflows/${encodeURIComponent(workflowId)}/releases/${encodeURIComponent(releaseId)}/rollback`, { method: 'POST', body: '{}' }); }
export async function getGeneratedClients(workflowId: string) { return request<{ clients: Record<string, string | object> }>(`/v1/workflows/${encodeURIComponent(workflowId)}/clients`); }
export async function rotateMcpKey() { return (await request<{ key: string }>('/v1/mcp/key', { method: 'POST', body: '{}' })).key; }
