const { releaseSnapshot, normalizeWorkflowContract, normalizeModelPolicy, normalizeContextPolicy, fingerprint } = require('./contract');
const { generatedClients } = require('./clients');

const ENVIRONMENTS = ['draft', 'test', 'staging', 'production'];
class WorkflowPlatformService {
  constructor({ store, loadWorkflow, clock = () => new Date().toISOString() }) { Object.assign(this, { store, loadWorkflow, clock }); }
  async configure(uid, workflowId, fields) { const workflow = await this.loadWorkflow(uid, workflowId); return this.store.patchWorkflow(uid, workflowId, { contract: normalizeWorkflowContract({ ...workflow, contract: fields.contract }), modelPolicy: normalizeModelPolicy({ ...workflow, modelPolicy: fields.modelPolicy }), contextPolicy: normalizeContextPolicy({ ...workflow, contextPolicy: fields.contextPolicy }), regressionCases: Array.isArray(fields.regressionCases) ? fields.regressionCases.slice(0, 100) : workflow.regressionCases || [] }); }
  async createRelease(uid, workflowId, fields = {}) { const workflow = await this.loadWorkflow(uid, workflowId); const snapshot = releaseSnapshot(workflow, { createdAt: this.clock(), createdBy: uid, notes: fields.notes }); const id = `rel-${snapshot.fingerprint.slice(0, 16)}`; const release = { ...snapshot, id, environment: 'draft', state: 'immutable', regression: null }; return this.store.saveRelease(uid, workflowId, release); }
  async recordRegression(uid, workflowId, releaseId, regression) { const release = await this.store.getRelease(uid, workflowId, releaseId); if (!release) throw new Error('Release not found.'); const testRecord = { ...regression, fingerprint: fingerprint(regression), completedAt: this.clock() }; await this.store.releases(uid, workflowId).doc(releaseId).set({ regression: testRecord }, { merge: true }); return testRecord; }
  async promote(uid, workflowId, releaseId, environment) { if (!ENVIRONMENTS.includes(environment) || environment === 'draft') throw new Error('Promotion target must be test, staging, or production.'); const [release, workflow] = await Promise.all([this.store.getRelease(uid, workflowId, releaseId), this.loadWorkflow(uid, workflowId)]); if (!release) throw new Error('Release not found.'); if (!release.regression?.passed) throw new Error('Release must pass its regression gate before promotion.'); if (environment === 'staging' && workflow.environments?.test !== releaseId) throw new Error('Promote this release to test before staging.'); if (environment === 'production' && workflow.environments?.staging !== releaseId) throw new Error('Promote this release to staging before production.'); const patch = { environments: { ...(workflow.environments || {}), [environment]: releaseId }, environmentPromotions: { ...(workflow.environmentPromotions || {}), [environment]: { releaseId, promotedAt: this.clock(), promotedBy: uid } } }; if (environment === 'production') patch.activeProductionReleaseId = releaseId; await this.store.patchWorkflow(uid, workflowId, patch); return { ...release, environment }; }
  async rollback(uid, workflowId, releaseId) { const [release, workflow] = await Promise.all([this.store.getRelease(uid, workflowId, releaseId), this.loadWorkflow(uid, workflowId)]); if (!release || !release.regression?.passed) throw new Error('Rollback target must be a tested release.'); await this.store.patchWorkflow(uid, workflowId, { activeProductionReleaseId: releaseId, environments: { ...(workflow.environments || {}), production: releaseId }, lastRollbackAt: this.clock(), lastRollbackBy: uid }); return release; }
  clients(baseUrl, workflow) { return generatedClients(baseUrl, workflow, normalizeWorkflowContract(workflow)); }
}
module.exports = { ENVIRONMENTS, WorkflowPlatformService };
