const { FirestoreMemoryStore, MemoryService, createMemoryRouter } = require('../../memory-engine');

function installMemoryOverlay({ app, express, db, authenticateUser }) {
  if (!app || !express || !db || !authenticateUser) throw new Error('Memory overlay requires app, Express, database, and auth.');
  const service = new MemoryService({ store: new FirestoreMemoryStore(db) });
  app.use('/v1/memories', async (req, res, next) => { try { req.uid = await authenticateUser(req); next(); } catch (error) { res.status(error.status || 401).json({ success: false, error: error.message }); } }, createMemoryRouter({ express, service, requireUser: async (req) => req.uid }));
  return { service, async prepareWorkflow(uid, workflow) { let targetDomain = ''; const urlNode = (workflow.nodes || []).find((node) => node.data?.url); try { targetDomain = new URL(urlNode?.data?.url).hostname; } catch {} const retrieval = await service.retrieve(uid, { workflowId: workflow.id, operationName: workflow.operationName || '', targetDomain, tags: workflow.tags || [] }, { limit: 12 }); if (!retrieval.memories.length) return { workflow, memoryIds: [], retrieval }; const memoryContext = retrieval.memories.map((memory) => ({ id: memory.id, type: memory.type, key: memory.key, value: memory.value, confidence: memory.confidence, provenance: memory.provenance })); let foundMission = false; const nodes = (workflow.nodes || []).map((node) => { if (node.type !== 'mission') return node; foundMission = true; return { ...node, data: { ...(node.data || {}), prompt: `${node.data?.prompt || ''}\n\nApproved Stanley memory (structured, tenant-scoped):\n${JSON.stringify(memoryContext)}`.trim() } }; }); if (!foundMission) nodes.unshift({ id: `memory-context-${workflow.id}`, type: 'mission', label: 'Approved memory context', data: { prompt: `Approved Stanley memory (structured, tenant-scoped):\n${JSON.stringify(memoryContext)}` } }); return { workflow: { ...workflow, nodes, memoryContext: memoryContext.map(({ id, type, key, confidence }) => ({ id, type, key, confidence })) }, memoryIds: memoryContext.map((memory) => memory.id), retrieval }; }, recordOutcome: (uid, ids, success) => service.recordOutcome(uid, ids, success) };
}

module.exports = { installMemoryOverlay };
