const { providerFor, requiredVaultRefs } = require('./providers');

const R = 'read'; const W = 'write';
const ARTIFACT_REQUESTS = {
  drive_upload_file: { encoding: 'raw', defaultQuery: { uploadType: 'media' } },
  dropbox_upload_file: { encoding: 'raw', argumentHeader: 'Dropbox-API-Arg' },
  box_upload_file: { encoding: 'multipart', fileField: 'file', metadataField: 'attributes' },
  openai_audio_transcription: { encoding: 'multipart', fileField: 'file' },
};
const ARTIFACT_RESPONSES = {
  drive_download_file: { defaultQuery: { alt: 'media' } },
  dropbox_download_file: { argumentHeader: 'Dropbox-API-Arg' },
};
const definitions = [
  ['gmail_list_messages','GET','/messages',R], ['gmail_send_email','POST','/messages/send',W], ['gmail_get_thread','GET','/threads/{threadId}',R], ['gmail_create_draft','POST','/drafts',W], ['gmail_archive_message','POST','/messages/{messageId}/modify',W], ['gmail_trash_message','POST','/messages/{messageId}/trash',W], ['gmail_add_label','POST','/messages/{messageId}/modify',W], ['gmail_remove_label','POST','/messages/{messageId}/modify',W], ['gmail_list_drafts','GET','/drafts',R], ['gmail_get_profile','GET','/profile',R],
  ['sheets_append_row','POST','/{spreadsheetId}/values/{range}:append',W], ['sheets_get_values','GET','/{spreadsheetId}/values/{range}',R], ['sheets_update_row','PUT','/{spreadsheetId}/values/{range}',W], ['sheets_create_spreadsheet','POST','',W], ['sheets_clear_values','POST','/{spreadsheetId}/values/{range}:clear',W], ['sheets_list_sheets','GET','/{spreadsheetId}',R], ['sheets_get_spreadsheet_info','GET','/{spreadsheetId}',R], ['sheets_delete_row','POST','/{spreadsheetId}:batchUpdate',W], ['sheets_copy_spreadsheet','POST','https://www.googleapis.com/drive/v3/files/{fileId}/copy',W], ['sheets_add_sheet','POST','/{spreadsheetId}:batchUpdate',W],
  ['calendar_create_event','POST','/calendars/{calendarId}/events',W], ['calendar_list_events','GET','/calendars/{calendarId}/events',R], ['calendar_delete_event','DELETE','/calendars/{calendarId}/events/{eventId}',W], ['calendar_update_event','PATCH','/calendars/{calendarId}/events/{eventId}',W], ['calendar_get_event','GET','/calendars/{calendarId}/events/{eventId}',R], ['calendar_quick_add','POST','/calendars/{calendarId}/events/quickAdd',W], ['calendar_list_calendars','GET','/users/me/calendarList',R], ['calendar_clear_primary','POST','/calendars/primary/clear',W],
  ['drive_upload_file','POST','https://www.googleapis.com/upload/drive/v3/files',W], ['drive_list_files','GET','/files',R], ['drive_create_folder','POST','/files',W], ['drive_delete_file','DELETE','/files/{fileId}',W], ['drive_download_file','GET','/files/{fileId}',R], ['drive_share_file','POST','/files/{fileId}/permissions',W], ['drive_copy_file','POST','/files/{fileId}/copy',W], ['drive_get_metadata','GET','/files/{fileId}',R],
  ['slack_post_message','POST','/chat.postMessage',W], ['slack_create_channel','POST','/conversations.create',W], ['slack_invite_user','POST','/conversations.invite',W], ['slack_add_reaction','POST','/reactions.add',W], ['slack_list_channels','GET','/conversations.list',R], ['slack_get_user_profile','GET','/users.profile.get',R], ['slack_update_status','POST','/users.profile.set',W], ['slack_remove_reaction','POST','/reactions.remove',W], ['slack_set_topic','POST','/conversations.setTopic',W],
  ['shopify_list_orders','GET','/orders.json',R], ['shopify_create_product','POST','/products.json',W], ['shopify_get_customer','GET','/customers/{customerId}.json',R], ['shopify_update_inventory','POST','/inventory_levels/set.json',W], ['shopify_list_products','GET','/products.json',R], ['shopify_create_order','POST','/draft_orders.json',W], ['shopify_update_price','PUT','/variants/{variantId}.json',W], ['shopify_delete_product','DELETE','/products/{productId}.json',W], ['shopify_create_customer','POST','/customers.json',W], ['shopify_list_fulfillments','GET','/fulfillment_services.json',R],
  ['notion_create_page','POST','/pages',W], ['notion_list_databases','POST','/search',R], ['notion_update_block','PATCH','/blocks/{blockId}',W], ['notion_query_database','POST','/databases/{databaseId}/query',R], ['notion_get_database','GET','/databases/{databaseId}',R], ['notion_append_block_children','PATCH','/blocks/{blockId}/children',W], ['notion_search_pages','POST','/search',R], ['notion_delete_page','PATCH','/pages/{pageId}',W], ['notion_archive_block','DELETE','/blocks/{blockId}',W],
  ['hubspot_create_contact','POST','/crm/v3/objects/contacts',W], ['hubspot_get_deal','GET','/crm/v3/objects/deals/{dealId}',R], ['hubspot_update_company','PATCH','/crm/v3/objects/companies/{companyId}',W], ['hubspot_list_contacts','GET','/crm/v3/objects/contacts',R], ['hubspot_list_deals','GET','/crm/v3/objects/deals',R], ['hubspot_create_company','POST','/crm/v3/objects/companies',W], ['hubspot_get_contact','GET','/crm/v3/objects/contacts/{contactId}',R], ['hubspot_create_ticket','POST','/crm/v3/objects/tickets',W], ['hubspot_list_tickets','GET','/crm/v3/objects/tickets',R], ['hubspot_update_contact_status','PATCH','/crm/v3/objects/contacts/{contactId}',W],
  ['github_create_issue','POST','/repos/{owner}/{repo}/issues',W], ['github_list_commits','GET','/repos/{owner}/{repo}/commits',R], ['github_create_repo','POST','/user/repos',W], ['github_create_pr','POST','/repos/{owner}/{repo}/pulls',W], ['github_add_collaborator','PUT','/repos/{owner}/{repo}/collaborators/{username}',W], ['github_list_issues','GET','/repos/{owner}/{repo}/issues',R], ['github_merge_pr','PUT','/repos/{owner}/{repo}/pulls/{pullNumber}/merge',W], ['github_get_contents','GET','/repos/{owner}/{repo}/contents/{filePath}',R], ['github_list_repos','GET','/user/repos',R], ['github_create_branch','POST','/repos/{owner}/{repo}/git/refs',W],
  ['twilio_send_sms','POST','/Messages.json',W], ['twilio_make_call','POST','/Calls.json',W], ['twilio_list_sms','GET','/Messages.json',R], ['twilio_buy_number','POST','/IncomingPhoneNumbers.json',W], ['twilio_get_balance','GET','https://api.twilio.com/2010-04-01/Accounts/{accountSid}/Balance.json',R], ['twilio_redirect_call','POST','/Calls/{callSid}.json',W],
  ['stripe_list_payments','GET','/charges',R], ['stripe_create_customer','POST','/customers',W], ['stripe_create_invoice','POST','/invoices',W], ['stripe_list_customers','GET','/customers',R], ['stripe_retrieve_charge','GET','/charges/{chargeId}',R], ['stripe_refund_charge','POST','/refunds',W], ['stripe_create_product','POST','/products',W], ['stripe_create_price','POST','/prices',W], ['stripe_list_invoices','GET','/invoices',R],
  ['mailchimp_add_subscriber','PUT','/lists/{listId}/members/{subscriberHash}',W], ['mailchimp_send_campaign','POST','/campaigns/{campaignId}/actions/send',W], ['mailchimp_remove_subscriber','PATCH','/lists/{listId}/members/{subscriberHash}',W], ['mailchimp_list_members','GET','/lists/{listId}/members',R], ['mailchimp_create_campaign','POST','/campaigns',W], ['mailchimp_create_list','POST','/lists',W],
  ['discord_send_channel_message','POST','/channels/{channelId}/messages',W], ['discord_add_role','PUT','/guilds/{guildId}/members/{userId}/roles/{roleId}',W], ['discord_remove_role','DELETE','/guilds/{guildId}/members/{userId}/roles/{roleId}',W], ['discord_kick_member','DELETE','/guilds/{guildId}/members/{userId}',W], ['discord_list_members','GET','/guilds/{guildId}/members',R], ['discord_create_invite','POST','/channels/{channelId}/invites',W], ['discord_create_channel','POST','/guilds/{guildId}/channels',W],
  ['trello_create_card','POST','/cards',W], ['trello_move_card','PUT','/cards/{cardId}',W], ['trello_delete_card','DELETE','/cards/{cardId}',W], ['trello_create_list','POST','/lists',W], ['trello_get_board_lists','GET','/boards/{boardId}/lists',R], ['trello_add_comment','POST','/cards/{cardId}/actions/comments',W],
  ['airtable_create_record','POST','/{baseId}/{tableId}',W], ['airtable_list_records','GET','/{baseId}/{tableId}',R], ['airtable_update_record','PATCH','/{baseId}/{tableId}/{recordId}',W], ['airtable_delete_record','DELETE','/{baseId}/{tableId}/{recordId}',W], ['airtable_get_record','GET','/{baseId}/{tableId}/{recordId}',R],
  ['jira_create_issue','POST','/issue',W], ['jira_update_ticket','PUT','/issue/{issueIdOrKey}',W], ['jira_add_comment','POST','/issue/{issueIdOrKey}/comment',W], ['jira_list_projects','GET','/project/search',R], ['jira_assign_issue','PUT','/issue/{issueIdOrKey}/assignee',W], ['jira_transition_issue','POST','/issue/{issueIdOrKey}/transitions',W],
  ['openai_chat_completion','POST','/responses',W], ['openai_image_generation','POST','/images/generations',W], ['openai_audio_transcription','POST','/audio/transcriptions',W], ['openai_embeddings','POST','/embeddings',W], ['openai_create_finetune','POST','/fine_tuning/jobs',W],
  ['salesforce_create_lead','POST','/sobjects/Lead',W], ['salesforce_get_account','GET','/sobjects/Account/{accountId}',R], ['salesforce_update_contact','PATCH','/sobjects/Contact/{contactId}',W], ['salesforce_list_leads','GET','/query',R], ['salesforce_create_opportunity','POST','/sobjects/Opportunity',W], ['salesforce_update_task','PATCH','/sobjects/Task/{taskId}',W], ['salesforce_delete_record','DELETE','/sobjects/{objectType}/{recordId}',W],
  ['asana_create_task','POST','/tasks',W], ['asana_list_projects','GET','/projects',R], ['asana_update_task_status','PUT','/tasks/{taskGid}',W], ['asana_add_subtask','POST','/tasks/{taskGid}/subtasks',W], ['asana_create_project','POST','/projects',W], ['asana_assign_task','PUT','/tasks/{taskGid}',W],
  ['linear_create_issue','POST','/graphql',W], ['linear_update_issue','POST','/graphql',W], ['linear_list_teams','POST','/graphql',R], ['linear_list_cycles','POST','/graphql',R], ['linear_assign_ticket','POST','/graphql',W], ['linear_link_issue','POST','/graphql',W],
  ['zoom_create_meeting','POST','/users/{userId}/meetings',W], ['zoom_list_meetings','GET','/users/{userId}/meetings',R], ['zoom_delete_meeting','DELETE','/meetings/{meetingId}',W], ['zoom_get_recording','GET','/meetings/{meetingId}/recordings',R], ['zoom_add_registrant','POST','/meetings/{meetingId}/registrants',W],
  ['zendesk_create_ticket','POST','/tickets.json',W], ['zendesk_update_ticket','PUT','/tickets/{ticketId}.json',W], ['zendesk_list_users','GET','/users.json',R], ['zendesk_get_ticket_info','GET','/tickets/{ticketId}.json',R], ['zendesk_assign_ticket','PUT','/tickets/{ticketId}.json',W],
  ['clickup_create_task','POST','/list/{listId}/task',W], ['clickup_list_folders','GET','/space/{spaceId}/folder',R], ['clickup_create_list','POST','/folder/{folderId}/list',W], ['clickup_update_task_status','PUT','/task/{taskId}',W], ['clickup_track_time','POST','/team/{teamId}/time_entries',W],
  ['figma_get_file','GET','/files/{fileKey}',R], ['figma_get_comments','GET','/files/{fileKey}/comments',R], ['figma_post_comment','POST','/files/{fileKey}/comments',W], ['figma_list_projects','GET','/teams/{teamId}/projects',R],
  ['docusign_send_envelope','POST','/envelopes',W], ['docusign_list_envelopes','GET','/envelopes',R], ['docusign_get_status','GET','/envelopes/{envelopeId}',R], ['docusign_create_template','POST','/templates',W],
  ['intercom_create_conversation','POST','/conversations',W], ['intercom_reply_conversation','POST','/conversations/{conversationId}/reply',W], ['intercom_list_users','GET','/contacts',R], ['intercom_get_user_info','GET','/contacts/{contactId}',R],
  ['pipedrive_create_deal','POST','/deals',W], ['pipedrive_update_deal','PUT','/deals/{dealId}',W], ['pipedrive_add_note','POST','/notes',W], ['pipedrive_list_activities','GET','/activities',R],
  ['dropbox_upload_file','POST','https://content.dropboxapi.com/2/files/upload',W], ['dropbox_list_folder','POST','/files/list_folder',R], ['dropbox_share_folder','POST','/sharing/share_folder',W], ['dropbox_download_file','POST','https://content.dropboxapi.com/2/files/download',R],
  ['box_upload_file','POST','https://upload.box.com/api/2.0/files/content',W], ['box_list_folder','GET','/folders/{folderId}/items',R], ['box_get_file_link','PUT','/files/{fileId}',W], ['box_delete_item','DELETE','/{itemType}/{itemId}',W],
  ['quickbooks_create_customer','POST','/customer',W], ['quickbooks_create_invoice','POST','/invoice',W], ['quickbooks_get_payment','GET','/payment/{paymentId}',R], ['quickbooks_list_vendor_bills','GET','/query',R],
  ['xero_create_invoice','POST','/Invoices',W], ['xero_list_bank_accounts','GET','/Accounts',R], ['xero_create_contact','POST','/Contacts',W], ['xero_get_categories','GET','/TrackingCategories',R],
  ['mailgun_send_email','POST','/messages',W], ['mailgun_list_logs','GET','/events',R], ['mailgun_validate_email','GET','https://api.mailgun.net/v4/address/validate',R],
  ['sendgrid_send_mail','POST','/mail/send',W], ['sendgrid_list_bounces','GET','/suppression/bounces',R], ['sendgrid_add_contact','PUT','/marketing/contacts',W],
  ['activecampaign_create_contact','POST','/contacts',W], ['activecampaign_add_to_list','POST','/contactLists',W], ['activecampaign_trigger_automation','POST','/contactAutomations',W],
  ['twitter_post_tweet','POST','/tweets',W], ['twitter_delete_tweet','DELETE','/tweets/{tweetId}',W], ['twitter_get_tweets','GET','/users/{userId}/tweets',R],
  ['facebook_post_page_feed','POST','/{pageId}/feed',W], ['facebook_upload_photo','POST','/{pageId}/photos',W], ['facebook_get_insights','GET','/{pageId}/insights',R],
  ['pinterest_create_pin','POST','/pins',W], ['pinterest_get_boards','GET','/boards',R], ['pinterest_delete_pin','DELETE','/pins/{pinId}',W],
  ['freshworks_create_ticket','POST','/tickets',W], ['freshworks_get_customer_info','GET','/contacts/{contactId}',R], ['freshworks_list_agents','GET','/agents',R],
  ['basecamp_create_todo','POST','/buckets/{projectId}/todolists/{todoListId}/todos.json',W], ['basecamp_list_todo_lists','GET','/buckets/{projectId}/todolists.json',R], ['basecamp_post_message','POST','/buckets/{projectId}/message_boards/{messageBoardId}/messages.json',W],
  ['teams_post_channel_message','POST','/teams/{teamId}/channels/{channelId}/messages',W], ['teams_create_chat','POST','/chats',W], ['teams_list_channels','GET','/teams/{teamId}/channels',R],
];

function title(id) { return id.split('_').slice(1).map((part) => part[0].toUpperCase() + part.slice(1)).join(' '); }
function pathFields(path) { return [...String(path).matchAll(/\{([A-Za-z][A-Za-z0-9]*)\}/g)].map((match) => match[1]).filter((field) => !['apiVersion'].includes(field)); }
function connectionFields(provider) {
  const source = [provider.baseUrl, ...Object.values(provider.headers || {})].join(' ');
  return [...new Set([...source.matchAll(/\{(?:connection\.)?([A-Za-z][A-Za-z0-9]*)\}/g)].map((match) => match[1]))]
    .filter((field) => provider.connectionDefaults?.[field] === undefined);
}
function compile([id, method, path, readWrite]) {
  const provider = providerFor(id); if (!provider) throw new Error(`Provider missing for ${id}.`);
  const requiredPath = pathFields(path).filter((field) => !String(provider.baseUrl).includes(`{${field}}`));
  const requiredConnection = connectionFields(provider);
  const artifactRequest = ARTIFACT_REQUESTS[id]; const artifactResponse = ARTIFACT_RESPONSES[id];
  const requiredInput = [...(requiredConnection.length ? ['connection'] : []), ...(requiredPath.length ? ['path'] : []), ...(artifactRequest ? ['artifactId'] : [])];
  return {
    schemaVersion: 1, id, operationName: id, name: `${provider.app}: ${title(id)}`, app: provider.app,
    method, path, readWrite, approvalRequired: readWrite === W, requiredVaultRefs: requiredVaultRefs(provider),
    inputSchema: { type: 'object', required: requiredInput, properties: { connection: { type: 'object', required: requiredConnection, properties: Object.fromEntries(requiredConnection.map((field) => [field, { type: ['string', 'number'], minLength: 1 }])) }, path: { type: 'object', required: requiredPath, properties: Object.fromEntries(requiredPath.map((field) => [field, { type: ['string', 'number'], minLength: 1 }])) }, query: { type: 'object' }, body: {}, headers: { type: 'object' }, artifactId: { type: 'string', minLength: 1 } }, additionalProperties: false },
    outputSchema: artifactResponse ? { type: 'object', required: ['id', 'name', 'mimeType', 'size'], properties: { id: { type: 'string' }, name: { type: 'string' }, mimeType: { type: 'string' }, size: { type: 'number' } } } : {},
    ...(artifactRequest ? { artifactRequest } : {}), ...(artifactResponse ? { artifactResponse } : {}),
  };
}

const OPERATIONS = definitions.map(compile); const BY_ID = new Map(OPERATIONS.map((operation) => [operation.id, operation]));
if (BY_ID.size !== definitions.length) throw new Error('Native integration operation ids must be unique.');
function getOperation(id) { return BY_ID.get(id) || null; }

module.exports = { OPERATIONS, connectionFields, getOperation, pathFields };
