const PROVIDERS = {
  gmail: { app: 'Gmail', baseUrl: 'https://gmail.googleapis.com/gmail/v1/users/me', auth: { type: 'bearer', vaultRef: 'GoogleOAuthToken' } },
  sheets: { app: 'Google Sheets', baseUrl: 'https://sheets.googleapis.com/v4/spreadsheets', auth: { type: 'bearer', vaultRef: 'GoogleOAuthToken' } },
  calendar: { app: 'Google Calendar', baseUrl: 'https://www.googleapis.com/calendar/v3', auth: { type: 'bearer', vaultRef: 'GoogleOAuthToken' } },
  drive: { app: 'Google Drive', baseUrl: 'https://www.googleapis.com/drive/v3', auth: { type: 'bearer', vaultRef: 'GoogleOAuthToken' } },
  slack: { app: 'Slack', baseUrl: 'https://slack.com/api', auth: { type: 'bearer', vaultRef: 'SlackToken' } },
  shopify: { app: 'Shopify', baseUrl: 'https://{shop}.myshopify.com/admin/api/{apiVersion}', connectionDefaults: { apiVersion: '2026-07' }, allowedHostSuffix: '.myshopify.com', auth: { type: 'header', name: 'X-Shopify-Access-Token', vaultRef: 'ShopifyAccessToken' } },
  notion: { app: 'Notion', baseUrl: 'https://api.notion.com/v1', auth: { type: 'bearer', vaultRef: 'NotionToken' }, headers: { 'Notion-Version': '2022-06-28' } },
  hubspot: { app: 'HubSpot', baseUrl: 'https://api.hubapi.com', auth: { type: 'bearer', vaultRef: 'HubSpotToken' } },
  github: { app: 'GitHub', baseUrl: 'https://api.github.com', auth: { type: 'bearer', vaultRef: 'GitHubToken' }, headers: { Accept: 'application/vnd.github+json', 'X-GitHub-Api-Version': '2022-11-28' } },
  twilio: { app: 'Twilio', baseUrl: 'https://api.twilio.com/2010-04-01/Accounts/{accountSid}', auth: { type: 'basic', usernameRef: 'TwilioAccountSid', passwordRef: 'TwilioAuthToken' }, requestEncoding: 'form' },
  stripe: { app: 'Stripe', baseUrl: 'https://api.stripe.com/v1', auth: { type: 'bearer', vaultRef: 'StripeSecretKey' }, requestEncoding: 'form' },
  mailchimp: { app: 'Mailchimp', baseUrl: 'https://{dataCenter}.api.mailchimp.com/3.0', allowedHostSuffix: '.api.mailchimp.com', auth: { type: 'basic', username: 'stanley', passwordRef: 'MailchimpApiKey' } },
  discord: { app: 'Discord', baseUrl: 'https://discord.com/api/v10', auth: { type: 'header', name: 'Authorization', prefix: 'Bot ', vaultRef: 'DiscordBotToken' } },
  trello: { app: 'Trello', baseUrl: 'https://api.trello.com/1', auth: { type: 'query', fields: { key: 'TrelloApiKey', token: 'TrelloToken' } } },
  airtable: { app: 'Airtable', baseUrl: 'https://api.airtable.com/v0', auth: { type: 'bearer', vaultRef: 'AirtableToken' } },
  jira: { app: 'Jira', baseUrl: 'https://{site}.atlassian.net/rest/api/3', allowedHostSuffix: '.atlassian.net', auth: { type: 'basic', usernameRef: 'JiraEmail', passwordRef: 'JiraApiToken' } },
  openai: { app: 'OpenAI', baseUrl: 'https://api.openai.com/v1', auth: { type: 'bearer', vaultRef: 'OpenAIApiKey' } },
  salesforce: { app: 'Salesforce', baseUrl: 'https://{instanceHost}/services/data/{apiVersion}', connectionDefaults: { apiVersion: 'v67.0' }, allowedHostSuffix: '.salesforce.com', auth: { type: 'bearer', vaultRef: 'SalesforceAccessToken' } },
  asana: { app: 'Asana', baseUrl: 'https://app.asana.com/api/1.0', auth: { type: 'bearer', vaultRef: 'AsanaToken' } },
  linear: { app: 'Linear', baseUrl: 'https://api.linear.app', auth: { type: 'bearer', vaultRef: 'LinearApiKey' } },
  zoom: { app: 'Zoom', baseUrl: 'https://api.zoom.us/v2', auth: { type: 'bearer', vaultRef: 'ZoomAccessToken' } },
  zendesk: { app: 'Zendesk', baseUrl: 'https://{subdomain}.zendesk.com/api/v2', allowedHostSuffix: '.zendesk.com', auth: { type: 'basic', usernameRef: 'ZendeskEmail', usernameSuffix: '/token', passwordRef: 'ZendeskApiToken' } },
  clickup: { app: 'ClickUp', baseUrl: 'https://api.clickup.com/api/v2', auth: { type: 'header', name: 'Authorization', vaultRef: 'ClickUpToken' } },
  figma: { app: 'Figma', baseUrl: 'https://api.figma.com/v1', auth: { type: 'header', name: 'X-Figma-Token', vaultRef: 'FigmaToken' } },
  docusign: { app: 'DocuSign', baseUrl: 'https://{accountBaseHost}/restapi/v2.1/accounts/{accountId}', allowedHostSuffix: '.docusign.net', auth: { type: 'bearer', vaultRef: 'DocuSignAccessToken' } },
  intercom: { app: 'Intercom', baseUrl: 'https://api.intercom.io', auth: { type: 'bearer', vaultRef: 'IntercomToken' }, headers: { 'Intercom-Version': '2.11' } },
  pipedrive: { app: 'Pipedrive', baseUrl: 'https://api.pipedrive.com/v1', auth: { type: 'query', fields: { api_token: 'PipedriveApiToken' } } },
  dropbox: { app: 'Dropbox', baseUrl: 'https://api.dropboxapi.com/2', auth: { type: 'bearer', vaultRef: 'DropboxAccessToken' } },
  box: { app: 'Box', baseUrl: 'https://api.box.com/2.0', auth: { type: 'bearer', vaultRef: 'BoxAccessToken' } },
  quickbooks: { app: 'QuickBooks', baseUrl: 'https://quickbooks.api.intuit.com/v3/company/{realmId}', auth: { type: 'bearer', vaultRef: 'QuickBooksAccessToken' } },
  xero: { app: 'Xero', baseUrl: 'https://api.xero.com/api.xro/2.0', auth: { type: 'bearer', vaultRef: 'XeroAccessToken' }, headers: { 'Xero-Tenant-Id': '{connection.tenantId}' } },
  mailgun: { app: 'Mailgun', baseUrl: 'https://api.mailgun.net/v3/{domain}', auth: { type: 'basic', username: 'api', passwordRef: 'MailgunApiKey' }, requestEncoding: 'form' },
  sendgrid: { app: 'SendGrid', baseUrl: 'https://api.sendgrid.com/v3', auth: { type: 'bearer', vaultRef: 'SendGridApiKey' } },
  activecampaign: { app: 'ActiveCampaign', baseUrl: 'https://{account}.api-us1.com/api/3', allowedHostSuffix: '.api-us1.com', auth: { type: 'header', name: 'Api-Token', vaultRef: 'ActiveCampaignToken' } },
  twitter: { app: 'Twitter/X', baseUrl: 'https://api.x.com/2', auth: { type: 'bearer', vaultRef: 'TwitterAccessToken' } },
  facebook: { app: 'Facebook Graph', baseUrl: 'https://graph.facebook.com/{apiVersion}', connectionDefaults: { apiVersion: 'v23.0' }, auth: { type: 'query', fields: { access_token: 'FacebookAccessToken' } } },
  pinterest: { app: 'Pinterest', baseUrl: 'https://api.pinterest.com/v5', auth: { type: 'bearer', vaultRef: 'PinterestAccessToken' } },
  freshworks: { app: 'Freshworks', baseUrl: 'https://{domain}.freshdesk.com/api/v2', allowedHostSuffix: '.freshdesk.com', auth: { type: 'basic', usernameRef: 'FreshworksApiKey', password: 'X' } },
  basecamp: { app: 'Basecamp', baseUrl: 'https://3.basecampapi.com/{accountId}', auth: { type: 'bearer', vaultRef: 'BasecampAccessToken' } },
  teams: { app: 'Microsoft Teams', baseUrl: 'https://graph.microsoft.com/v1.0', auth: { type: 'bearer', vaultRef: 'MicrosoftAccessToken' } },
};

function providerFor(operationId) { return PROVIDERS[operationId.split('_')[0]] || null; }
function requiredVaultRefs(provider) { const auth = provider?.auth || {}; return [...new Set([auth.vaultRef, auth.usernameRef, auth.passwordRef, ...Object.values(auth.fields || {})].filter(Boolean))]; }

module.exports = { PROVIDERS, providerFor, requiredVaultRefs };
