const clone = (value) => value === undefined ? undefined : JSON.parse(JSON.stringify(value));

class MemorySkillStore {
  constructor() { this.versions = new Map(); this.active = new Map(); }
  key(tenantId, skillId, version) { return `${tenantId}:${skillId}:${version}`; }
  rootKey(tenantId, skillId) { return `${tenantId}:${skillId}`; }
  async create(skill) { const key = this.key(skill.tenantId, skill.skillId, skill.version); if (this.versions.has(key)) throw new Error('Skill version already exists.'); this.versions.set(key, clone(skill)); return clone(skill); }
  async saveDraft(skill) { const key = this.key(skill.tenantId, skill.skillId, skill.version); const current = this.versions.get(key); if (!current) throw new Error('Skill not found.'); if (['active', 'retired'].includes(current.state)) throw new Error('Active skill versions are immutable.'); this.versions.set(key, clone(skill)); return clone(skill); }
  async get(tenantId, skillId, version) { return clone(this.versions.get(this.key(tenantId, skillId, version)) || null); }
  async list(tenantId, { workflowId, state } = {}) { return [...this.versions.values()].filter((item) => item.tenantId === tenantId && (!workflowId || item.workflowId === workflowId) && (!state || item.state === state)).map(clone); }
  async listActive(tenantId, { workflowId } = {}) { return [...this.active.entries()].filter(([key]) => key.startsWith(`${tenantId}:`)).map(([key, version]) => this.versions.get(`${key}:${version}`)).filter((item) => item && (!workflowId || item.workflowId === workflowId)).map(clone); }
  async activate(skill) { const active = { ...clone(skill), state: 'active', activatedAt: skill.activatedAt || new Date().toISOString() }; this.versions.set(this.key(skill.tenantId, skill.skillId, skill.version), active); this.active.set(this.rootKey(skill.tenantId, skill.skillId), skill.version); return clone(active); }
  async setActiveVersion(tenantId, skillId, version) { const skill = await this.get(tenantId, skillId, version); if (!skill || skill.state !== 'active') throw new Error('Rollback target must be active.'); this.active.set(this.rootKey(tenantId, skillId), version); return skill; }
  async recordExecution(tenantId, skillId, version, record) { const current = this.versions.get(this.key(tenantId, skillId, version)); if (!current) throw new Error('Skill not found.'); current.successCount = Number(current.successCount || 0) + (record.success ? 1 : 0); current.failureCount = Number(current.failureCount || 0) + (record.success ? 0 : 1); current.driftCount = Number(current.driftCount || 0) + (record.drift ? 1 : 0); current.latencyMsTotal = Number(current.latencyMsTotal || 0) + Number(record.durationMs || 0); current.executionCostMicros = Number(current.executionCostMicros || 0) + Number(record.executionCostMicros || 0); current.modelCallsSaved = Number(current.modelCallsSaved || 0) + Number(record.modelCallsSaved || 0); current.lastExecutionAt = record.occurredAt; return clone(current); }
}

class FirestoreSkillStore {
  constructor(db, options = {}) { if (!db) throw new Error('FirestoreSkillStore requires a database.'); this.db = db; this.clock = options.clock || (() => new Date().toISOString()); }
  root(tenantId) { return this.db.collection('stanley_users').doc(tenantId).collection('skills'); }
  meta(tenantId, skillId) { return this.root(tenantId).doc(skillId); }
  version(tenantId, skillId, version) { return this.meta(tenantId, skillId).collection('versions').doc(version); }
  async create(skill) { const ref = this.version(skill.tenantId, skill.skillId, skill.version); const snap = await ref.get(); if (snap.exists) throw new Error('Skill version already exists.'); await ref.set(clone(skill)); await this.meta(skill.tenantId, skill.skillId).set({ skillId: skill.skillId, workflowId: skill.workflowId, name: skill.name, updatedAt: this.clock() }, { merge: true }); return clone(skill); }
  async saveDraft(skill) { const ref = this.version(skill.tenantId, skill.skillId, skill.version); const snap = await ref.get(); if (!snap.exists) throw new Error('Skill not found.'); if (['active', 'retired'].includes(snap.data().state)) throw new Error('Active skill versions are immutable.'); await ref.set(clone(skill)); return clone(skill); }
  async get(tenantId, skillId, version) { const snap = await this.version(tenantId, skillId, version).get(); return snap.exists ? { ...snap.data(), version: snap.id } : null; }
  async list(tenantId, { workflowId, state, limit = 100 } = {}) { const safeLimit = Math.min(limit, 200); let metaQuery = this.root(tenantId); if (workflowId) metaQuery = metaQuery.where('workflowId', '==', workflowId); const metas = await metaQuery.limit(safeLimit).get(); const groups = await Promise.all(metas.docs.map(async (meta) => { let query = meta.ref.collection('versions'); if (state) query = query.where('state', '==', state); const snap = await query.limit(safeLimit).get(); return snap.docs.map((doc) => ({ ...doc.data(), version: doc.id })); })); return groups.flat().sort((a, b) => String(b.updatedAt || b.createdAt || '').localeCompare(String(a.updatedAt || a.createdAt || ''))).slice(0, safeLimit); }
  async listActive(tenantId, { workflowId, limit = 100 } = {}) { let query = this.root(tenantId); if (workflowId) query = query.where('workflowId', '==', workflowId); const metas = await query.limit(Math.min(limit, 200)).get(); const skills = []; for (const doc of metas.docs) { const version = doc.data().activeVersion; if (version) { const skill = await this.get(tenantId, doc.id, version); if (skill) skills.push(skill); } } return skills; }
  async activate(skill) { const active = { ...clone(skill), state: 'active', activatedAt: skill.activatedAt || this.clock() }; await this.version(skill.tenantId, skill.skillId, skill.version).set(active); await this.meta(skill.tenantId, skill.skillId).set({ activeVersion: skill.version, updatedAt: this.clock() }, { merge: true }); return active; }
  async setActiveVersion(tenantId, skillId, version) { const skill = await this.get(tenantId, skillId, version); if (!skill || skill.state !== 'active') throw new Error('Rollback target must be active.'); await this.meta(tenantId, skillId).set({ activeVersion: version, rollbackAt: this.clock(), updatedAt: this.clock() }, { merge: true }); return skill; }
  async recordExecution(tenantId, skillId, version, record) { const ref = this.version(tenantId, skillId, version); const snap = await ref.get(); if (!snap.exists) throw new Error('Skill not found.'); const current = snap.data(); const patch = { successCount: Number(current.successCount || 0) + (record.success ? 1 : 0), failureCount: Number(current.failureCount || 0) + (record.success ? 0 : 1), driftCount: Number(current.driftCount || 0) + (record.drift ? 1 : 0), latencyMsTotal: Number(current.latencyMsTotal || 0) + Number(record.durationMs || 0), executionCostMicros: Number(current.executionCostMicros || 0) + Number(record.executionCostMicros || 0), modelCallsSaved: Number(current.modelCallsSaved || 0) + Number(record.modelCallsSaved || 0), lastExecutionAt: record.occurredAt }; await ref.set(patch, { merge: true }); return { ...current, ...patch }; }
}

module.exports = { FirestoreSkillStore, MemorySkillStore };
