const crypto = require('crypto');
const { hash } = require('../../connector-engine');

const RUN_STATES = new Set(['created', 'running', 'waiting', 'queued', 'completed', 'failed', 'cancelled', 'compensating', 'compensated']);
const WAIT_TYPES = new Set(['approval', 'webhook', 'date', 'reply', 'file', 'external_state']);
const TRANSITIONS = Object.freeze({ created: ['running', 'cancelled'], running: ['waiting', 'completed', 'failed', 'compensating', 'cancelled'], waiting: ['queued', 'failed', 'cancelled'], queued: ['running', 'cancelled'], failed: ['compensating'], compensating: ['compensated', 'failed'], completed: [], cancelled: [], compensated: [] });
function nowIso(clock) { return (clock || (() => new Date().toISOString()))(); }
function appendTimeline(run, event, clock) { const sequence = Number(run.timeline?.length || 0) + 1; return [...(run.timeline || []), { sequence, at: nowIso(clock), ...event }]; }
function transition(run, state, event, clock) { if (!RUN_STATES.has(state) || !(TRANSITIONS[run.state] || []).includes(state)) throw new Error(`Run cannot transition from ${run.state} to ${state}.`); return { ...run, state, timeline: appendTimeline(run, { kind: 'state_transition', from: run.state, to: state, ...event }, clock), updatedAt: nowIso(clock) }; }
function createRun(fields, options = {}) { const now = nowIso(options.clock); const run = { schemaVersion: 1, id: fields.id || crypto.randomBytes(10).toString('hex'), tenantId: fields.tenantId, workflowId: fields.workflowId, workflowFingerprint: fields.workflowFingerprint, state: 'created', cursor: null, nodeState: {}, waits: {}, effectLedger: {}, compensationStack: [], processedEventIds: [], timeline: [], createdAt: now, updatedAt: now }; if (!run.tenantId || !run.workflowId || !run.workflowFingerprint) throw new Error('Durable run requires tenant, workflow, and fingerprint.'); run.timeline = appendTimeline(run, { kind: 'run_created' }, options.clock); return run; }
function waitRecord(run, node, spec, checkpoint, options = {}) { if (!WAIT_TYPES.has(spec.type)) throw new Error(`Unsupported wait type: ${spec.type}`); const createdAt = nowIso(options.clock); const correlationId = spec.correlationId || crypto.randomBytes(12).toString('hex'); const token = spec.token || crypto.randomBytes(24).toString('base64url'); const requiredEvents = Math.max(1, Math.min(Number(spec.requiredEvents || 1), 100)); const timeoutAt = spec.timeoutAt || (spec.timeoutMs ? new Date(Date.parse(createdAt) + Number(spec.timeoutMs)).toISOString() : null); return { id: `wait-${hash({ runId: run.id, nodeId: node.id, correlationId }).slice(0, 20)}`, runId: run.id, nodeId: node.id, type: spec.type, state: 'pending', correlationId, tokenHash: hash(token), requiredEvents, receivedEvents: [], resumeWhen: spec.resumeWhen || null, wakeAt: spec.wakeAt || null, timeoutAt, escalation: spec.escalation || null, checkpoint, createdAt, token }; }
module.exports = { RUN_STATES, TRANSITIONS, WAIT_TYPES, appendTimeline, createRun, transition, waitRecord };
