const clone = (value) => value === undefined ? undefined : JSON.parse(JSON.stringify(value)); class MonitoringStore { constructor() { this.records = new Map(); this.alerts = new Map(); } key(uid, workflowId) { return `${uid}:${workflowId}`; } async append(uid, workflowId, record, limit = 500) { const key = this.key(uid, workflowId); const records = [...(this.records.get(key) || []), clone(record)].slice(-limit); this.records.set(key, records); return clone(records); } async listRecords(uid, workflowId) { return clone(this.records.get(this.key(uid, workflowId)) || []); } async saveAlert(uid, alert) { this.alerts.set(`${uid}:${alert.id}`, clone(alert)); return clone(alert); } async listAlerts(uid) { return [...this.alerts.values()].filter((a) => a.tenantId === uid).map(clone); } }
class FirestoreMonitoringStore { constructor(db) { this.db = db; } root(uid, workflowId) { return this.db.collection('stanley_users').doc(uid).collection('workflow_monitoring').doc(workflowId); } async append(uid, workflowId, record) { await this.root(uid, workflowId).collection('outcomes').doc(record.id).set(clone(record)); return this.listRecords(uid, workflowId); } async listRecords(uid, workflowId, limit = 500) { const snap = await this.root(uid, workflowId).collection('outcomes').orderBy('occurredAt', 'desc').limit(limit).get(); return snap.docs.map((doc) => ({ id: doc.id, ...doc.data() })).reverse(); } async saveAlert(uid, alert) { await this.db.collection('stanley_users').doc(uid).collection('monitoring_alerts').doc(alert.id).set(clone(alert)); return alert; } async listAlerts(uid, limit = 100) { const snap = await this.db.collection('stanley_users').doc(uid).collection('monitoring_alerts').orderBy('createdAt', 'desc').limit(limit).get(); return snap.docs.map((doc) => ({ id: doc.id, ...doc.data() })); } }
FirestoreMonitoringStore.prototype.monitorCollection = function monitorCollection(uid) { return this.db.collection('stanley_users').doc(uid).collection('outcome_monitors'); };
FirestoreMonitoringStore.prototype.saveMonitor = async function saveMonitor(uid, monitor) { await this.monitorCollection(uid).doc(monitor.id).set(clone(monitor)); return monitor; };
FirestoreMonitoringStore.prototype.getMonitor = async function getMonitor(uid, id) { const snap = await this.monitorCollection(uid).doc(id).get(); return snap.exists ? { id: snap.id, ...snap.data() } : null; };
FirestoreMonitoringStore.prototype.listMonitors = async function listMonitors(uid) { const snap = await this.monitorCollection(uid).limit(200).get(); return snap.docs.map((doc) => ({ id: doc.id, ...doc.data() })); };
FirestoreMonitoringStore.prototype.saveEvaluation = async function saveEvaluation(uid, result) { await this.monitorCollection(uid).doc(result.monitorId).collection('evaluations').doc(result.id).set(clone(result)); return result; };
FirestoreMonitoringStore.prototype.dueMonitorTenants = async function dueMonitorTenants(now) { const snap = await this.db.collectionGroup('outcome_monitors').where('state', '==', 'active').limit(1000).get(); return [...new Set(snap.docs.map((doc) => doc.data()).filter((monitor) => monitor.nextEvaluationAt <= now).map((monitor) => monitor.tenantId))]; };
module.exports = { FirestoreMonitoringStore, MonitoringStore };
