const { createTemplate, healthFrom, templateFromConnector, templateFromSkill } = require('./artifact');

class TemplateService {
  constructor({ store, connectorStore, skillStore, clock = () => new Date().toISOString(), publicPublisher = () => false }) { this.store = store; this.connectorStore = connectorStore; this.skillStore = skillStore; this.clock = clock; this.publicPublisher = publicPublisher; }
  async list(tenantId, filters) { const items = await this.store.list(tenantId, filters); return Promise.all(items.map((item) => this.refreshHealth(item))); }
  async refreshHealth(item) { let source = null; if (item.provenance?.type === 'connector') source = await this.connectorStore.get(item.tenantId, item.provenance.id, item.provenance.version); if (item.provenance?.type === 'skill') source = await this.skillStore.get(item.tenantId, item.provenance.id, item.provenance.version); if (!source) return item; const current = healthFrom(source); return { ...item, health: { ...item.health, ...current, usageCount: Number(item.health?.usageCount || 0), compatibility: source.fingerprint === item.provenance.fingerprint ? 'current' : 'review_required' } }; }
  async require(tenantId, templateId, version) { const item = await this.store.get(tenantId, templateId, version); if (!item) throw Object.assign(new Error('Template version not found.'), { status: 404 }); return item; }
  async fromConnector(tenantId, connectorId, version, options = {}) { const source = await this.connectorStore.get(tenantId, connectorId, version); if (!source) throw new Error('Connector version not found.'); return this.store.create(templateFromConnector(source, { ...options, createdBy: options.createdBy || tenantId, now: this.clock() })); }
  async fromSkill(tenantId, skillId, version, options = {}) { const source = await this.skillStore.get(tenantId, skillId, version); if (!source) throw new Error('Skill version not found.'); return this.store.create(templateFromSkill(source, { ...options, createdBy: options.createdBy || tenantId, now: this.clock() })); }
  async approve(tenantId, templateId, version, actor, note = '') { const item = await this.require(tenantId, templateId, version); if (item.state !== 'draft') throw new Error('Only draft templates can be approved.'); const now = this.clock(); return this.store.save({ ...item, state: 'approved', approvalHistory: [...item.approvalHistory, { action: 'approved', actor, note, at: now, fingerprint: item.fingerprint }], updatedAt: now }); }
  async updateDraft(tenantId, templateId, version, changes) { const item = await this.require(tenantId, templateId, version); if (item.tenantId !== tenantId) throw Object.assign(new Error('Only the template owner may edit it.'), { status: 403 }); if (item.state !== 'draft') throw new Error('Only draft templates can be edited.'); const allowed = Object.fromEntries(Object.entries(changes || {}).filter(([key]) => ['name', 'description', 'category', 'visibility'].includes(key))); return this.store.save(createTemplate({ ...item, ...allowed }, { now: this.clock() })); }
  async publish(tenantId, templateId, version, actor) { const item = await this.require(tenantId, templateId, version); if (item.tenantId !== tenantId) throw Object.assign(new Error('Only the template owner may publish it.'), { status: 403 }); if (item.state !== 'approved') throw new Error('Only approved templates can be published.'); if (item.visibility === 'public' && !this.publicPublisher(actor)) throw Object.assign(new Error('Public template publication requires catalog administrator approval.'), { status: 403 }); const now = this.clock(); const published = { ...item, state: 'published', publishedAt: now, updatedAt: now, approvalHistory: [...item.approvalHistory, { action: 'published', actor, at: now, fingerprint: item.fingerprint }] }; return this.store.publish ? this.store.publish(published) : this.store.save(published); }
  async retire(tenantId, templateId, version, actor) { const item = await this.require(tenantId, templateId, version); if (item.tenantId !== tenantId) throw Object.assign(new Error('Only the template owner may retire it.'), { status: 403 }); if (item.state !== 'published') throw new Error('Only published templates can be retired.'); const now = this.clock(); const retired = { ...item, state: 'retired', retiredAt: now, updatedAt: now, approvalHistory: [...item.approvalHistory, { action: 'retired', actor, at: now }] }; return this.store.retire ? this.store.retire(retired) : this.store.save(retired); }
  async recordUse(tenantId, templateId, version) { const item = await this.require(tenantId, templateId, version); if (item.state !== 'published') throw new Error('Only published templates can be used.'); if (this.store.incrementUse) return this.store.incrementUse(item); return this.store.save({ ...item, health: { ...item.health, usageCount: Number(item.health?.usageCount || 0) + 1 }, updatedAt: this.clock() }); }
  async createManual(tenantId, fields, actor) { return this.store.create(createTemplate({ ...fields, tenantId, createdBy: actor }, { now: this.clock() })); }
}

module.exports = { TemplateService };
